// Generated automatically by nearley, version 2.16.0
// http://github.com/Hardmath123/nearley
(function () {
function id(x) { return x[0]; }
 function rejecter(d, l, reject) { return reject; } 
 function joiner(d) { return d.join(''); } var grammar = {
    Lexer: undefined,
    ParserRules: [
    {"name": "main", "symbols": ["input"]},
    {"name": "input$ebnf$1", "symbols": ["input_section"], "postprocess": id},
    {"name": "input$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "input", "symbols": ["input$ebnf$1"]},
    {"name": "input_section", "symbols": ["input_section_part"]},
    {"name": "input_section", "symbols": ["input_section", "input_section_part"]},
    {"name": "input_section_part$ebnf$1", "symbols": ["input_elements"], "postprocess": id},
    {"name": "input_section_part$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "input_section_part", "symbols": ["input_section_part$ebnf$1", "new_line", "pp_directive"]},
    {"name": "input_elements", "symbols": ["input_element", "input_elements", "input_element"]},
    {"name": "input_element", "symbols": ["whitespace", "comment", "token"]},
    {"name": "charriage_return_character", "symbols": [{"literal":"\r"}]},
    {"name": "line_feed_character", "symbols": [{"literal":"\n"}]},
    {"name": "next_line_character", "symbols": [{"literal":""}]},
    {"name": "line_separator_character$string$1", "symbols": [{"literal":"\\"}, {"literal":"u"}, {"literal":"2"}, {"literal":"0"}, {"literal":"2"}, {"literal":"8"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "line_separator_character", "symbols": ["line_separator_character$string$1"]},
    {"name": "paragraph_separator_character$string$1", "symbols": [{"literal":"\\"}, {"literal":"u"}, {"literal":"2"}, {"literal":"0"}, {"literal":"2"}, {"literal":"9"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "paragraph_separator_character", "symbols": ["paragraph_separator_character$string$1"]},
    {"name": "new_line", "symbols": ["charriage_return_character"]},
    {"name": "new_line", "symbols": ["line_feed_character"]},
    {"name": "new_line", "symbols": ["charriage_return_character", "line_feed_character"]},
    {"name": "new_line", "symbols": ["next_line_character"]},
    {"name": "new_line", "symbols": ["line_separator_character"]},
    {"name": "new_line", "symbols": ["paragraph_separator_character"]},
    {"name": "comment", "symbols": ["single_line_comment"]},
    {"name": "comment", "symbols": ["delimited_comment"]},
    {"name": "single_line_comment$string$1", "symbols": [{"literal":"/"}, {"literal":"/"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "single_line_comment$ebnf$1", "symbols": ["input_characters"], "postprocess": id},
    {"name": "single_line_comment$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "single_line_comment", "symbols": ["single_line_comment$string$1", "single_line_comment$ebnf$1"]},
    {"name": "input_characters", "symbols": ["input_character"]},
    {"name": "input_characters", "symbols": ["input_characters", "input_character"]},
    {"name": "input_character", "symbols": ["new_line"], "postprocess": rejecter},
    {"name": "input_character", "symbols": ["unicode_character"]},
    {"name": "unicode_character", "symbols": [/[\u0000-\uFFFF]/]},
    {"name": "new_line_character", "symbols": ["charriage_return_character"]},
    {"name": "new_line_character", "symbols": ["line_feed_character"]},
    {"name": "new_line_character", "symbols": ["next_line_character"]},
    {"name": "new_line_character", "symbols": ["line_separator_character"]},
    {"name": "new_line_character", "symbols": ["paragraph_separator_character"]},
    {"name": "delimited_comment$string$1", "symbols": [{"literal":"/"}, {"literal":"*"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "delimited_comment$ebnf$1", "symbols": ["delimited_comment_text"], "postprocess": id},
    {"name": "delimited_comment$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "delimited_comment", "symbols": ["delimited_comment$string$1", "delimited_comment$ebnf$1", "asterisks", {"literal":"/"}]},
    {"name": "delimited_comment_text", "symbols": ["delimited_comment_section"]},
    {"name": "delimited_comment_text", "symbols": ["delimited_comment_text", "delimited_comment_section"]},
    {"name": "delimited_comment_section", "symbols": [{"literal":"/"}]},
    {"name": "delimited_comment_section$ebnf$1", "symbols": ["asterisks"], "postprocess": id},
    {"name": "delimited_comment_section$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "delimited_comment_section", "symbols": ["delimited_comment_section$ebnf$1", "not_slash_or_asterisk"]},
    {"name": "asterisks", "symbols": [{"literal":"*"}]},
    {"name": "asterisks", "symbols": ["asterisks", {"literal":"*"}]},
    {"name": "not_slash_or_asterisk", "symbols": [{"literal":"/"}], "postprocess": rejecter},
    {"name": "not_slash_or_asterisk", "symbols": [{"literal":"*"}], "postprocess": rejecter},
    {"name": "not_slash_or_asterisk", "symbols": ["unicode_character"]},
    {"name": "whitespace", "symbols": ["whitespace_character"]},
    {"name": "whitespace", "symbols": ["whitespace", "whitespace_character"]},
    {"name": "whitespace_character", "symbols": [/[\p{Z}]/]},
    {"name": "whitespace_character", "symbols": ["horizontal_tab_character"]},
    {"name": "whitespace_character", "symbols": ["vertical_tab_character"]},
    {"name": "whitespace_character", "symbols": ["form_feed_character"]},
    {"name": "horizontal_tab_character", "symbols": [{"literal":"\t"}]},
    {"name": "vertical_tab_character", "symbols": [{"literal":"\u000b"}]},
    {"name": "form_feed_character", "symbols": [{"literal":"\f"}]},
    {"name": "token", "symbols": ["identifier"]},
    {"name": "token", "symbols": ["keyword"]},
    {"name": "token", "symbols": ["integer_literal"]},
    {"name": "token", "symbols": ["real_literal"]},
    {"name": "token", "symbols": ["character_literal"]},
    {"name": "token", "symbols": ["string_literal"]},
    {"name": "token", "symbols": ["operator_or_punctuator"]},
    {"name": "unicode_escape_sequence$string$1", "symbols": [{"literal":"\\"}, {"literal":"u"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "unicode_escape_sequence$string$2", "symbols": [{"literal":"\\"}, {"literal":"U"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "unicode_escape_sequence", "symbols": ["unicode_escape_sequence$string$1", "hex_digit", "hex_digit", "hex_digit", "hex_digit", "unicode_escape_sequence$string$2", "hex_digit", "hex_digit", "hex_digit", "hex_digit", "hex_digit", "hex_digit", "hex_digit", "hex_digit"]},
    {"name": "identifier", "symbols": ["available_identifier"]},
    {"name": "identifier", "symbols": [{"literal":"@"}, "identifier_or_keyword"]},
    {"name": "available_identifier", "symbols": ["keyword"], "postprocess": rejecter},
    {"name": "available_identifier", "symbols": ["identifier_or_keyword"]},
    {"name": "identifier_or_keyword$ebnf$1", "symbols": ["identifier_part_characters"], "postprocess": id},
    {"name": "identifier_or_keyword$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "identifier_or_keyword", "symbols": ["identifier_start_character", "identifier_or_keyword$ebnf$1"]},
    {"name": "identifier_start_character", "symbols": ["letter_character"]},
    {"name": "identifier_start_character", "symbols": ["underscore_character"]},
    {"name": "underscore_character", "symbols": [{"literal":"_"}]},
    {"name": "identifier_part_characters", "symbols": ["identifier_part_character"]},
    {"name": "identifier_part_characters", "symbols": ["identifier_part_characters", "identifier_part_character"]},
    {"name": "identifier_part_character", "symbols": ["letter_character"]},
    {"name": "identifier_part_character", "symbols": ["decimal_digit_character"]},
    {"name": "identifier_part_character", "symbols": ["connecting_character"]},
    {"name": "identifier_part_character", "symbols": ["combining_character"]},
    {"name": "identifier_part_character", "symbols": ["formatting_character"]},
    {"name": "letter_character", "symbols": [/[\p{Lu}]/]},
    {"name": "letter_character", "symbols": [/[\p{Ll}]/]},
    {"name": "letter_character", "symbols": [/[\p{Lt}]/]},
    {"name": "letter_character", "symbols": [/[\p{Lm}]/]},
    {"name": "letter_character", "symbols": [/[\p{Lo}]/]},
    {"name": "letter_character", "symbols": [/[\p{Nl}]/]},
    {"name": "combining_character", "symbols": [/[\p{Mn}]/]},
    {"name": "combining_character", "symbols": [/[\p{Mc}]/]},
    {"name": "decimal_digit_character", "symbols": [/[\p{Nd}]/]},
    {"name": "connecting_character", "symbols": [/[\p{Pc}]/]},
    {"name": "formatting_character", "symbols": [/[\p{Cf}]/]},
    {"name": "keyword$string$1", "symbols": [{"literal":"a"}, {"literal":"b"}, {"literal":"s"}, {"literal":"t"}, {"literal":"r"}, {"literal":"a"}, {"literal":"c"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "keyword", "symbols": ["keyword$string$1"]},
    {"name": "keyword$string$2", "symbols": [{"literal":"a"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "keyword", "symbols": ["keyword$string$2"]},
    {"name": "keyword$string$3", "symbols": [{"literal":"b"}, {"literal":"a"}, {"literal":"s"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "keyword", "symbols": ["keyword$string$3"]},
    {"name": "keyword$string$4", "symbols": [{"literal":"b"}, {"literal":"o"}, {"literal":"o"}, {"literal":"l"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "keyword", "symbols": ["keyword$string$4"]},
    {"name": "keyword$string$5", "symbols": [{"literal":"b"}, {"literal":"r"}, {"literal":"e"}, {"literal":"a"}, {"literal":"k"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "keyword", "symbols": ["keyword$string$5"]},
    {"name": "keyword$string$6", "symbols": [{"literal":"b"}, {"literal":"y"}, {"literal":"t"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "keyword", "symbols": ["keyword$string$6"]},
    {"name": "keyword$string$7", "symbols": [{"literal":"c"}, {"literal":"a"}, {"literal":"s"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "keyword", "symbols": ["keyword$string$7"]},
    {"name": "keyword$string$8", "symbols": [{"literal":"c"}, {"literal":"a"}, {"literal":"t"}, {"literal":"c"}, {"literal":"h"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "keyword", "symbols": ["keyword$string$8"]},
    {"name": "keyword$string$9", "symbols": [{"literal":"c"}, {"literal":"h"}, {"literal":"a"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "keyword", "symbols": ["keyword$string$9"]},
    {"name": "keyword$string$10", "symbols": [{"literal":"c"}, {"literal":"h"}, {"literal":"e"}, {"literal":"c"}, {"literal":"k"}, {"literal":"e"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "keyword", "symbols": ["keyword$string$10"]},
    {"name": "keyword$string$11", "symbols": [{"literal":"c"}, {"literal":"l"}, {"literal":"a"}, {"literal":"s"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "keyword", "symbols": ["keyword$string$11"]},
    {"name": "keyword$string$12", "symbols": [{"literal":"c"}, {"literal":"o"}, {"literal":"n"}, {"literal":"s"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "keyword", "symbols": ["keyword$string$12"]},
    {"name": "keyword$string$13", "symbols": [{"literal":"c"}, {"literal":"o"}, {"literal":"n"}, {"literal":"t"}, {"literal":"i"}, {"literal":"n"}, {"literal":"u"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "keyword", "symbols": ["keyword$string$13"]},
    {"name": "keyword$string$14", "symbols": [{"literal":"d"}, {"literal":"e"}, {"literal":"c"}, {"literal":"i"}, {"literal":"m"}, {"literal":"a"}, {"literal":"l"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "keyword", "symbols": ["keyword$string$14"]},
    {"name": "keyword$string$15", "symbols": [{"literal":"d"}, {"literal":"e"}, {"literal":"f"}, {"literal":"a"}, {"literal":"u"}, {"literal":"l"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "keyword", "symbols": ["keyword$string$15"]},
    {"name": "keyword$string$16", "symbols": [{"literal":"d"}, {"literal":"e"}, {"literal":"l"}, {"literal":"e"}, {"literal":"g"}, {"literal":"a"}, {"literal":"t"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "keyword", "symbols": ["keyword$string$16"]},
    {"name": "keyword$string$17", "symbols": [{"literal":"d"}, {"literal":"o"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "keyword", "symbols": ["keyword$string$17"]},
    {"name": "keyword$string$18", "symbols": [{"literal":"d"}, {"literal":"o"}, {"literal":"u"}, {"literal":"b"}, {"literal":"l"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "keyword", "symbols": ["keyword$string$18"]},
    {"name": "keyword$string$19", "symbols": [{"literal":"e"}, {"literal":"l"}, {"literal":"s"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "keyword", "symbols": ["keyword$string$19"]},
    {"name": "keyword$string$20", "symbols": [{"literal":"e"}, {"literal":"n"}, {"literal":"u"}, {"literal":"m"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "keyword", "symbols": ["keyword$string$20"]},
    {"name": "keyword$string$21", "symbols": [{"literal":"e"}, {"literal":"v"}, {"literal":"e"}, {"literal":"n"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "keyword", "symbols": ["keyword$string$21"]},
    {"name": "keyword$string$22", "symbols": [{"literal":"e"}, {"literal":"x"}, {"literal":"p"}, {"literal":"l"}, {"literal":"i"}, {"literal":"c"}, {"literal":"i"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "keyword", "symbols": ["keyword$string$22"]},
    {"name": "keyword$string$23", "symbols": [{"literal":"e"}, {"literal":"x"}, {"literal":"t"}, {"literal":"e"}, {"literal":"r"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "keyword", "symbols": ["keyword$string$23"]},
    {"name": "keyword$string$24", "symbols": [{"literal":"f"}, {"literal":"a"}, {"literal":"l"}, {"literal":"s"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "keyword", "symbols": ["keyword$string$24"]},
    {"name": "keyword$string$25", "symbols": [{"literal":"f"}, {"literal":"i"}, {"literal":"n"}, {"literal":"a"}, {"literal":"l"}, {"literal":"l"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "keyword", "symbols": ["keyword$string$25"]},
    {"name": "keyword$string$26", "symbols": [{"literal":"f"}, {"literal":"i"}, {"literal":"x"}, {"literal":"e"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "keyword", "symbols": ["keyword$string$26"]},
    {"name": "keyword$string$27", "symbols": [{"literal":"f"}, {"literal":"l"}, {"literal":"o"}, {"literal":"a"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "keyword", "symbols": ["keyword$string$27"]},
    {"name": "keyword$string$28", "symbols": [{"literal":"f"}, {"literal":"o"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "keyword", "symbols": ["keyword$string$28"]},
    {"name": "keyword$string$29", "symbols": [{"literal":"f"}, {"literal":"o"}, {"literal":"r"}, {"literal":"e"}, {"literal":"a"}, {"literal":"c"}, {"literal":"h"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "keyword", "symbols": ["keyword$string$29"]},
    {"name": "keyword$string$30", "symbols": [{"literal":"g"}, {"literal":"o"}, {"literal":"t"}, {"literal":"o"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "keyword", "symbols": ["keyword$string$30"]},
    {"name": "keyword$string$31", "symbols": [{"literal":"i"}, {"literal":"f"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "keyword", "symbols": ["keyword$string$31"]},
    {"name": "keyword$string$32", "symbols": [{"literal":"i"}, {"literal":"m"}, {"literal":"p"}, {"literal":"l"}, {"literal":"i"}, {"literal":"c"}, {"literal":"i"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "keyword", "symbols": ["keyword$string$32"]},
    {"name": "keyword$string$33", "symbols": [{"literal":"i"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "keyword", "symbols": ["keyword$string$33"]},
    {"name": "keyword$string$34", "symbols": [{"literal":"i"}, {"literal":"n"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "keyword", "symbols": ["keyword$string$34"]},
    {"name": "keyword$string$35", "symbols": [{"literal":"i"}, {"literal":"n"}, {"literal":"t"}, {"literal":"e"}, {"literal":"r"}, {"literal":"f"}, {"literal":"a"}, {"literal":"c"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "keyword", "symbols": ["keyword$string$35"]},
    {"name": "keyword$string$36", "symbols": [{"literal":"i"}, {"literal":"n"}, {"literal":"t"}, {"literal":"e"}, {"literal":"r"}, {"literal":"n"}, {"literal":"a"}, {"literal":"l"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "keyword", "symbols": ["keyword$string$36"]},
    {"name": "keyword$string$37", "symbols": [{"literal":"i"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "keyword", "symbols": ["keyword$string$37"]},
    {"name": "keyword$string$38", "symbols": [{"literal":"l"}, {"literal":"o"}, {"literal":"c"}, {"literal":"k"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "keyword", "symbols": ["keyword$string$38"]},
    {"name": "keyword$string$39", "symbols": [{"literal":"l"}, {"literal":"o"}, {"literal":"n"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "keyword", "symbols": ["keyword$string$39"]},
    {"name": "keyword$string$40", "symbols": [{"literal":"n"}, {"literal":"a"}, {"literal":"m"}, {"literal":"e"}, {"literal":"s"}, {"literal":"p"}, {"literal":"a"}, {"literal":"c"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "keyword", "symbols": ["keyword$string$40"]},
    {"name": "keyword$string$41", "symbols": [{"literal":"n"}, {"literal":"e"}, {"literal":"w"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "keyword", "symbols": ["keyword$string$41"]},
    {"name": "keyword$string$42", "symbols": [{"literal":"n"}, {"literal":"u"}, {"literal":"l"}, {"literal":"l"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "keyword", "symbols": ["keyword$string$42"]},
    {"name": "keyword$string$43", "symbols": [{"literal":"o"}, {"literal":"b"}, {"literal":"j"}, {"literal":"e"}, {"literal":"c"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "keyword", "symbols": ["keyword$string$43"]},
    {"name": "keyword$string$44", "symbols": [{"literal":"o"}, {"literal":"p"}, {"literal":"e"}, {"literal":"r"}, {"literal":"a"}, {"literal":"t"}, {"literal":"o"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "keyword", "symbols": ["keyword$string$44"]},
    {"name": "keyword$string$45", "symbols": [{"literal":"o"}, {"literal":"u"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "keyword", "symbols": ["keyword$string$45"]},
    {"name": "keyword$string$46", "symbols": [{"literal":"o"}, {"literal":"v"}, {"literal":"e"}, {"literal":"r"}, {"literal":"r"}, {"literal":"i"}, {"literal":"d"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "keyword", "symbols": ["keyword$string$46"]},
    {"name": "keyword$string$47", "symbols": [{"literal":"p"}, {"literal":"a"}, {"literal":"r"}, {"literal":"a"}, {"literal":"m"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "keyword", "symbols": ["keyword$string$47"]},
    {"name": "keyword$string$48", "symbols": [{"literal":"p"}, {"literal":"r"}, {"literal":"i"}, {"literal":"v"}, {"literal":"a"}, {"literal":"t"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "keyword", "symbols": ["keyword$string$48"]},
    {"name": "keyword$string$49", "symbols": [{"literal":"p"}, {"literal":"r"}, {"literal":"o"}, {"literal":"t"}, {"literal":"e"}, {"literal":"c"}, {"literal":"t"}, {"literal":"e"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "keyword", "symbols": ["keyword$string$49"]},
    {"name": "keyword$string$50", "symbols": [{"literal":"p"}, {"literal":"u"}, {"literal":"b"}, {"literal":"l"}, {"literal":"i"}, {"literal":"c"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "keyword", "symbols": ["keyword$string$50"]},
    {"name": "keyword$string$51", "symbols": [{"literal":"r"}, {"literal":"e"}, {"literal":"a"}, {"literal":"d"}, {"literal":"o"}, {"literal":"n"}, {"literal":"l"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "keyword", "symbols": ["keyword$string$51"]},
    {"name": "keyword$string$52", "symbols": [{"literal":"r"}, {"literal":"e"}, {"literal":"f"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "keyword", "symbols": ["keyword$string$52"]},
    {"name": "keyword$string$53", "symbols": [{"literal":"r"}, {"literal":"e"}, {"literal":"t"}, {"literal":"u"}, {"literal":"r"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "keyword", "symbols": ["keyword$string$53"]},
    {"name": "keyword$string$54", "symbols": [{"literal":"s"}, {"literal":"b"}, {"literal":"y"}, {"literal":"t"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "keyword", "symbols": ["keyword$string$54"]},
    {"name": "keyword$string$55", "symbols": [{"literal":"s"}, {"literal":"e"}, {"literal":"a"}, {"literal":"l"}, {"literal":"e"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "keyword", "symbols": ["keyword$string$55"]},
    {"name": "keyword$string$56", "symbols": [{"literal":"s"}, {"literal":"h"}, {"literal":"o"}, {"literal":"r"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "keyword", "symbols": ["keyword$string$56"]},
    {"name": "keyword$string$57", "symbols": [{"literal":"s"}, {"literal":"i"}, {"literal":"z"}, {"literal":"e"}, {"literal":"o"}, {"literal":"f"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "keyword", "symbols": ["keyword$string$57"]},
    {"name": "keyword$string$58", "symbols": [{"literal":"s"}, {"literal":"t"}, {"literal":"a"}, {"literal":"c"}, {"literal":"k"}, {"literal":"a"}, {"literal":"l"}, {"literal":"l"}, {"literal":"o"}, {"literal":"c"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "keyword", "symbols": ["keyword$string$58"]},
    {"name": "keyword$string$59", "symbols": [{"literal":"s"}, {"literal":"t"}, {"literal":"a"}, {"literal":"t"}, {"literal":"i"}, {"literal":"c"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "keyword", "symbols": ["keyword$string$59"]},
    {"name": "keyword$string$60", "symbols": [{"literal":"s"}, {"literal":"t"}, {"literal":"r"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "keyword", "symbols": ["keyword$string$60"]},
    {"name": "keyword$string$61", "symbols": [{"literal":"s"}, {"literal":"t"}, {"literal":"r"}, {"literal":"u"}, {"literal":"c"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "keyword", "symbols": ["keyword$string$61"]},
    {"name": "keyword$string$62", "symbols": [{"literal":"s"}, {"literal":"w"}, {"literal":"i"}, {"literal":"t"}, {"literal":"c"}, {"literal":"h"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "keyword", "symbols": ["keyword$string$62"]},
    {"name": "keyword$string$63", "symbols": [{"literal":"t"}, {"literal":"h"}, {"literal":"i"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "keyword", "symbols": ["keyword$string$63"]},
    {"name": "keyword$string$64", "symbols": [{"literal":"t"}, {"literal":"h"}, {"literal":"r"}, {"literal":"o"}, {"literal":"w"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "keyword", "symbols": ["keyword$string$64"]},
    {"name": "keyword$string$65", "symbols": [{"literal":"t"}, {"literal":"r"}, {"literal":"u"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "keyword", "symbols": ["keyword$string$65"]},
    {"name": "keyword$string$66", "symbols": [{"literal":"t"}, {"literal":"r"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "keyword", "symbols": ["keyword$string$66"]},
    {"name": "keyword$string$67", "symbols": [{"literal":"t"}, {"literal":"y"}, {"literal":"p"}, {"literal":"e"}, {"literal":"o"}, {"literal":"f"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "keyword", "symbols": ["keyword$string$67"]},
    {"name": "keyword$string$68", "symbols": [{"literal":"u"}, {"literal":"i"}, {"literal":"n"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "keyword", "symbols": ["keyword$string$68"]},
    {"name": "keyword$string$69", "symbols": [{"literal":"u"}, {"literal":"l"}, {"literal":"o"}, {"literal":"n"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "keyword", "symbols": ["keyword$string$69"]},
    {"name": "keyword$string$70", "symbols": [{"literal":"u"}, {"literal":"n"}, {"literal":"c"}, {"literal":"h"}, {"literal":"e"}, {"literal":"c"}, {"literal":"k"}, {"literal":"e"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "keyword", "symbols": ["keyword$string$70"]},
    {"name": "keyword$string$71", "symbols": [{"literal":"u"}, {"literal":"n"}, {"literal":"s"}, {"literal":"a"}, {"literal":"f"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "keyword", "symbols": ["keyword$string$71"]},
    {"name": "keyword$string$72", "symbols": [{"literal":"u"}, {"literal":"s"}, {"literal":"h"}, {"literal":"o"}, {"literal":"r"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "keyword", "symbols": ["keyword$string$72"]},
    {"name": "keyword$string$73", "symbols": [{"literal":"u"}, {"literal":"s"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "keyword", "symbols": ["keyword$string$73"]},
    {"name": "keyword$string$74", "symbols": [{"literal":"v"}, {"literal":"i"}, {"literal":"r"}, {"literal":"t"}, {"literal":"u"}, {"literal":"a"}, {"literal":"l"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "keyword", "symbols": ["keyword$string$74"]},
    {"name": "keyword$string$75", "symbols": [{"literal":"v"}, {"literal":"o"}, {"literal":"i"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "keyword", "symbols": ["keyword$string$75"]},
    {"name": "keyword$string$76", "symbols": [{"literal":"v"}, {"literal":"o"}, {"literal":"l"}, {"literal":"a"}, {"literal":"t"}, {"literal":"i"}, {"literal":"l"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "keyword", "symbols": ["keyword$string$76"]},
    {"name": "keyword$string$77", "symbols": [{"literal":"w"}, {"literal":"h"}, {"literal":"i"}, {"literal":"l"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "keyword", "symbols": ["keyword$string$77"]},
    {"name": "contextual_keyword$string$1", "symbols": [{"literal":"a"}, {"literal":"d"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "contextual_keyword", "symbols": ["contextual_keyword$string$1"]},
    {"name": "contextual_keyword$string$2", "symbols": [{"literal":"a"}, {"literal":"l"}, {"literal":"i"}, {"literal":"a"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "contextual_keyword", "symbols": ["contextual_keyword$string$2"]},
    {"name": "contextual_keyword$string$3", "symbols": [{"literal":"a"}, {"literal":"s"}, {"literal":"c"}, {"literal":"e"}, {"literal":"n"}, {"literal":"d"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "contextual_keyword", "symbols": ["contextual_keyword$string$3"]},
    {"name": "contextual_keyword$string$4", "symbols": [{"literal":"a"}, {"literal":"s"}, {"literal":"y"}, {"literal":"n"}, {"literal":"c"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "contextual_keyword", "symbols": ["contextual_keyword$string$4"]},
    {"name": "contextual_keyword$string$5", "symbols": [{"literal":"a"}, {"literal":"w"}, {"literal":"a"}, {"literal":"i"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "contextual_keyword", "symbols": ["contextual_keyword$string$5"]},
    {"name": "contextual_keyword$string$6", "symbols": [{"literal":"b"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "contextual_keyword", "symbols": ["contextual_keyword$string$6"]},
    {"name": "contextual_keyword$string$7", "symbols": [{"literal":"d"}, {"literal":"e"}, {"literal":"s"}, {"literal":"c"}, {"literal":"e"}, {"literal":"n"}, {"literal":"d"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "contextual_keyword", "symbols": ["contextual_keyword$string$7"]},
    {"name": "contextual_keyword$string$8", "symbols": [{"literal":"d"}, {"literal":"y"}, {"literal":"n"}, {"literal":"a"}, {"literal":"m"}, {"literal":"i"}, {"literal":"c"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "contextual_keyword", "symbols": ["contextual_keyword$string$8"]},
    {"name": "contextual_keyword$string$9", "symbols": [{"literal":"e"}, {"literal":"q"}, {"literal":"u"}, {"literal":"a"}, {"literal":"l"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "contextual_keyword", "symbols": ["contextual_keyword$string$9"]},
    {"name": "contextual_keyword$string$10", "symbols": [{"literal":"f"}, {"literal":"r"}, {"literal":"o"}, {"literal":"m"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "contextual_keyword", "symbols": ["contextual_keyword$string$10"]},
    {"name": "contextual_keyword$string$11", "symbols": [{"literal":"g"}, {"literal":"e"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "contextual_keyword", "symbols": ["contextual_keyword$string$11"]},
    {"name": "contextual_keyword$string$12", "symbols": [{"literal":"g"}, {"literal":"l"}, {"literal":"o"}, {"literal":"b"}, {"literal":"a"}, {"literal":"l"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "contextual_keyword", "symbols": ["contextual_keyword$string$12"]},
    {"name": "contextual_keyword$string$13", "symbols": [{"literal":"g"}, {"literal":"r"}, {"literal":"o"}, {"literal":"u"}, {"literal":"p"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "contextual_keyword", "symbols": ["contextual_keyword$string$13"]},
    {"name": "contextual_keyword$string$14", "symbols": [{"literal":"i"}, {"literal":"n"}, {"literal":"t"}, {"literal":"o"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "contextual_keyword", "symbols": ["contextual_keyword$string$14"]},
    {"name": "contextual_keyword$string$15", "symbols": [{"literal":"j"}, {"literal":"o"}, {"literal":"i"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "contextual_keyword", "symbols": ["contextual_keyword$string$15"]},
    {"name": "contextual_keyword$string$16", "symbols": [{"literal":"l"}, {"literal":"e"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "contextual_keyword", "symbols": ["contextual_keyword$string$16"]},
    {"name": "contextual_keyword$string$17", "symbols": [{"literal":"o"}, {"literal":"r"}, {"literal":"d"}, {"literal":"e"}, {"literal":"r"}, {"literal":"b"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "contextual_keyword", "symbols": ["contextual_keyword$string$17"]},
    {"name": "contextual_keyword$string$18", "symbols": [{"literal":"p"}, {"literal":"a"}, {"literal":"r"}, {"literal":"t"}, {"literal":"i"}, {"literal":"a"}, {"literal":"l"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "contextual_keyword", "symbols": ["contextual_keyword$string$18"]},
    {"name": "contextual_keyword$string$19", "symbols": [{"literal":"r"}, {"literal":"e"}, {"literal":"m"}, {"literal":"o"}, {"literal":"v"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "contextual_keyword", "symbols": ["contextual_keyword$string$19"]},
    {"name": "contextual_keyword$string$20", "symbols": [{"literal":"s"}, {"literal":"e"}, {"literal":"l"}, {"literal":"e"}, {"literal":"c"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "contextual_keyword", "symbols": ["contextual_keyword$string$20"]},
    {"name": "contextual_keyword$string$21", "symbols": [{"literal":"s"}, {"literal":"e"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "contextual_keyword", "symbols": ["contextual_keyword$string$21"]},
    {"name": "contextual_keyword$string$22", "symbols": [{"literal":"v"}, {"literal":"a"}, {"literal":"l"}, {"literal":"u"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "contextual_keyword", "symbols": ["contextual_keyword$string$22"]},
    {"name": "contextual_keyword$string$23", "symbols": [{"literal":"v"}, {"literal":"a"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "contextual_keyword", "symbols": ["contextual_keyword$string$23"]},
    {"name": "contextual_keyword$string$24", "symbols": [{"literal":"w"}, {"literal":"h"}, {"literal":"e"}, {"literal":"r"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "contextual_keyword", "symbols": ["contextual_keyword$string$24"]},
    {"name": "contextual_keyword$string$25", "symbols": [{"literal":"y"}, {"literal":"i"}, {"literal":"e"}, {"literal":"l"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "contextual_keyword", "symbols": ["contextual_keyword$string$25"]},
    {"name": "literal", "symbols": ["boolean_literal"]},
    {"name": "literal", "symbols": ["integer_literal"]},
    {"name": "literal", "symbols": ["real_literal"]},
    {"name": "literal", "symbols": ["character_literal"]},
    {"name": "literal", "symbols": ["string_literal"]},
    {"name": "literal", "symbols": ["null_literal"]},
    {"name": "boolean_literal$string$1", "symbols": [{"literal":"t"}, {"literal":"r"}, {"literal":"u"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "boolean_literal", "symbols": ["boolean_literal$string$1"]},
    {"name": "boolean_literal$string$2", "symbols": [{"literal":"f"}, {"literal":"a"}, {"literal":"l"}, {"literal":"s"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "boolean_literal", "symbols": ["boolean_literal$string$2"]},
    {"name": "integer_literal", "symbols": ["decimal_integer_literal"]},
    {"name": "integer_literal", "symbols": ["hexadecimal_integer_literal"]},
    {"name": "decimal_integer_literal$ebnf$1", "symbols": ["integer_type_suffix"], "postprocess": id},
    {"name": "decimal_integer_literal$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "decimal_integer_literal", "symbols": ["decimal_digits", "decimal_integer_literal$ebnf$1"]},
    {"name": "decimal_digits", "symbols": ["decimal_digit"]},
    {"name": "decimal_digits", "symbols": ["decimal_digits", "decimal_digit"]},
    {"name": "decimal_digit", "symbols": [{"literal":"0"}]},
    {"name": "decimal_digit", "symbols": [{"literal":"1"}]},
    {"name": "decimal_digit", "symbols": [{"literal":"2"}]},
    {"name": "decimal_digit", "symbols": [{"literal":"3"}]},
    {"name": "decimal_digit", "symbols": [{"literal":"4"}]},
    {"name": "decimal_digit", "symbols": [{"literal":"5"}]},
    {"name": "decimal_digit", "symbols": [{"literal":"6"}]},
    {"name": "decimal_digit", "symbols": [{"literal":"7"}]},
    {"name": "decimal_digit", "symbols": [{"literal":"8"}]},
    {"name": "decimal_digit", "symbols": [{"literal":"9"}]},
    {"name": "integer_type_suffix", "symbols": [{"literal":"U"}]},
    {"name": "integer_type_suffix", "symbols": [{"literal":"u"}]},
    {"name": "integer_type_suffix", "symbols": [{"literal":"L"}]},
    {"name": "integer_type_suffix", "symbols": [{"literal":"l"}]},
    {"name": "integer_type_suffix$string$1", "symbols": [{"literal":"U"}, {"literal":"L"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "integer_type_suffix", "symbols": ["integer_type_suffix$string$1"]},
    {"name": "integer_type_suffix$string$2", "symbols": [{"literal":"U"}, {"literal":"l"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "integer_type_suffix", "symbols": ["integer_type_suffix$string$2"]},
    {"name": "integer_type_suffix$string$3", "symbols": [{"literal":"u"}, {"literal":"L"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "integer_type_suffix", "symbols": ["integer_type_suffix$string$3"]},
    {"name": "integer_type_suffix$string$4", "symbols": [{"literal":"u"}, {"literal":"l"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "integer_type_suffix", "symbols": ["integer_type_suffix$string$4"]},
    {"name": "integer_type_suffix$string$5", "symbols": [{"literal":"L"}, {"literal":"U"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "integer_type_suffix", "symbols": ["integer_type_suffix$string$5"]},
    {"name": "integer_type_suffix$string$6", "symbols": [{"literal":"L"}, {"literal":"u"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "integer_type_suffix", "symbols": ["integer_type_suffix$string$6"]},
    {"name": "integer_type_suffix$string$7", "symbols": [{"literal":"l"}, {"literal":"U"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "integer_type_suffix", "symbols": ["integer_type_suffix$string$7"]},
    {"name": "integer_type_suffix$string$8", "symbols": [{"literal":"l"}, {"literal":"u"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "integer_type_suffix", "symbols": ["integer_type_suffix$string$8"]},
    {"name": "hexadecimal_integer_literal$string$1", "symbols": [{"literal":"0"}, {"literal":"x"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "hexadecimal_integer_literal$ebnf$1", "symbols": ["integer_type_suffix"], "postprocess": id},
    {"name": "hexadecimal_integer_literal$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "hexadecimal_integer_literal", "symbols": ["hexadecimal_integer_literal$string$1", "hex_digits", "hexadecimal_integer_literal$ebnf$1"]},
    {"name": "hexadecimal_integer_literal$string$2", "symbols": [{"literal":"0"}, {"literal":"X"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "hexadecimal_integer_literal$ebnf$2", "symbols": ["integer_type_suffix"], "postprocess": id},
    {"name": "hexadecimal_integer_literal$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "hexadecimal_integer_literal", "symbols": ["hexadecimal_integer_literal$string$2", "hex_digits", "hexadecimal_integer_literal$ebnf$2"]},
    {"name": "hex_digits", "symbols": ["hex_digit"]},
    {"name": "hex_digits", "symbols": ["hex_digits", "hex_digit"]},
    {"name": "hex_digit", "symbols": [{"literal":"0"}]},
    {"name": "hex_digit", "symbols": [{"literal":"1"}]},
    {"name": "hex_digit", "symbols": [{"literal":"2"}]},
    {"name": "hex_digit", "symbols": [{"literal":"3"}]},
    {"name": "hex_digit", "symbols": [{"literal":"4"}]},
    {"name": "hex_digit", "symbols": [{"literal":"5"}]},
    {"name": "hex_digit", "symbols": [{"literal":"6"}]},
    {"name": "hex_digit", "symbols": [{"literal":"7"}]},
    {"name": "hex_digit", "symbols": [{"literal":"8"}]},
    {"name": "hex_digit", "symbols": [{"literal":"9"}]},
    {"name": "hex_digit", "symbols": [{"literal":"A"}]},
    {"name": "hex_digit", "symbols": [{"literal":"B"}]},
    {"name": "hex_digit", "symbols": [{"literal":"C"}]},
    {"name": "hex_digit", "symbols": [{"literal":"D"}]},
    {"name": "hex_digit", "symbols": [{"literal":"E"}]},
    {"name": "hex_digit", "symbols": [{"literal":"F"}]},
    {"name": "hex_digit", "symbols": [{"literal":"a"}]},
    {"name": "hex_digit", "symbols": [{"literal":"b"}]},
    {"name": "hex_digit", "symbols": [{"literal":"c"}]},
    {"name": "hex_digit", "symbols": [{"literal":"d"}]},
    {"name": "hex_digit", "symbols": [{"literal":"e"}]},
    {"name": "hex_digit", "symbols": [{"literal":"f"}]},
    {"name": "real_literal$ebnf$1", "symbols": ["exponent_part"], "postprocess": id},
    {"name": "real_literal$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "real_literal$ebnf$2", "symbols": ["real_type_suffix"], "postprocess": id},
    {"name": "real_literal$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "real_literal", "symbols": ["decimal_digits", {"literal":"."}, "decimal_digits", "real_literal$ebnf$1", "real_literal$ebnf$2"]},
    {"name": "real_literal$ebnf$3", "symbols": ["exponent_part"], "postprocess": id},
    {"name": "real_literal$ebnf$3", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "real_literal$ebnf$4", "symbols": ["real_type_suffix"], "postprocess": id},
    {"name": "real_literal$ebnf$4", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "real_literal", "symbols": [{"literal":"."}, "decimal_digits", "real_literal$ebnf$3", "real_literal$ebnf$4"]},
    {"name": "real_literal$ebnf$5", "symbols": ["real_type_suffix"], "postprocess": id},
    {"name": "real_literal$ebnf$5", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "real_literal", "symbols": ["decimal_digits", "exponent_part", "real_literal$ebnf$5"]},
    {"name": "real_literal", "symbols": ["decimal_digits", "real_type_suffix"]},
    {"name": "exponent_part$ebnf$1", "symbols": ["sign"], "postprocess": id},
    {"name": "exponent_part$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "exponent_part", "symbols": [{"literal":"e"}, "exponent_part$ebnf$1", "decimal_digits"]},
    {"name": "exponent_part$ebnf$2", "symbols": ["sign"], "postprocess": id},
    {"name": "exponent_part$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "exponent_part", "symbols": [{"literal":"E"}, "exponent_part$ebnf$2", "decimal_digits"]},
    {"name": "sign", "symbols": [{"literal":"+"}]},
    {"name": "sign", "symbols": [{"literal":"-"}]},
    {"name": "real_type_suffix", "symbols": [{"literal":"F"}]},
    {"name": "real_type_suffix", "symbols": [{"literal":"f"}]},
    {"name": "real_type_suffix", "symbols": [{"literal":"D"}]},
    {"name": "real_type_suffix", "symbols": [{"literal":"d"}]},
    {"name": "real_type_suffix", "symbols": [{"literal":"M"}]},
    {"name": "real_type_suffix", "symbols": [{"literal":"m"}]},
    {"name": "character_literal", "symbols": [{"literal":"'"}, "character", {"literal":"'"}]},
    {"name": "character", "symbols": ["single_character"]},
    {"name": "character", "symbols": ["simple_escape_sequence"]},
    {"name": "character", "symbols": ["hexadecimal_escape_sequence"]},
    {"name": "character", "symbols": ["unicode_escape_sequence"]},
    {"name": "single_character", "symbols": [{"literal":"'"}], "postprocess": rejecter},
    {"name": "single_character", "symbols": [{"literal":"\\"}], "postprocess": rejecter},
    {"name": "single_character", "symbols": ["new_line_character"], "postprocess": rejecter},
    {"name": "single_character", "symbols": ["character"]},
    {"name": "simple_escape_sequence$string$1", "symbols": [{"literal":"\\"}, {"literal":"'"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "simple_escape_sequence", "symbols": ["simple_escape_sequence$string$1"]},
    {"name": "simple_escape_sequence$string$2", "symbols": [{"literal":"\\"}, {"literal":"\""}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "simple_escape_sequence", "symbols": ["simple_escape_sequence$string$2"]},
    {"name": "simple_escape_sequence$string$3", "symbols": [{"literal":"\\"}, {"literal":"\\"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "simple_escape_sequence", "symbols": ["simple_escape_sequence$string$3"]},
    {"name": "simple_escape_sequence$string$4", "symbols": [{"literal":"\\"}, {"literal":"0"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "simple_escape_sequence", "symbols": ["simple_escape_sequence$string$4"]},
    {"name": "simple_escape_sequence$string$5", "symbols": [{"literal":"\\"}, {"literal":"a"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "simple_escape_sequence", "symbols": ["simple_escape_sequence$string$5"]},
    {"name": "simple_escape_sequence$string$6", "symbols": [{"literal":"\\"}, {"literal":"b"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "simple_escape_sequence", "symbols": ["simple_escape_sequence$string$6"]},
    {"name": "simple_escape_sequence$string$7", "symbols": [{"literal":"\\"}, {"literal":"f"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "simple_escape_sequence", "symbols": ["simple_escape_sequence$string$7"]},
    {"name": "simple_escape_sequence$string$8", "symbols": [{"literal":"\\"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "simple_escape_sequence", "symbols": ["simple_escape_sequence$string$8"]},
    {"name": "simple_escape_sequence$string$9", "symbols": [{"literal":"\\"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "simple_escape_sequence", "symbols": ["simple_escape_sequence$string$9"]},
    {"name": "simple_escape_sequence$string$10", "symbols": [{"literal":"\\"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "simple_escape_sequence", "symbols": ["simple_escape_sequence$string$10"]},
    {"name": "simple_escape_sequence$string$11", "symbols": [{"literal":"\\"}, {"literal":"v"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "simple_escape_sequence", "symbols": ["simple_escape_sequence$string$11"]},
    {"name": "hexadecimal_escape_sequence$string$1", "symbols": [{"literal":"\\"}, {"literal":"x"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "hexadecimal_escape_sequence$ebnf$1", "symbols": ["hex_digit"], "postprocess": id},
    {"name": "hexadecimal_escape_sequence$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "hexadecimal_escape_sequence$ebnf$2", "symbols": ["hex_digit"], "postprocess": id},
    {"name": "hexadecimal_escape_sequence$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "hexadecimal_escape_sequence$ebnf$3", "symbols": ["hex_digit"], "postprocess": id},
    {"name": "hexadecimal_escape_sequence$ebnf$3", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "hexadecimal_escape_sequence", "symbols": ["hexadecimal_escape_sequence$string$1", "hex_digit", "hexadecimal_escape_sequence$ebnf$1", "hexadecimal_escape_sequence$ebnf$2", "hexadecimal_escape_sequence$ebnf$3"]},
    {"name": "string_literal", "symbols": ["regular_string_literal"]},
    {"name": "string_literal", "symbols": ["verbatim_string_literal"]},
    {"name": "regular_string_literal$ebnf$1", "symbols": ["regular_string_literal_characters"], "postprocess": id},
    {"name": "regular_string_literal$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "regular_string_literal", "symbols": [{"literal":"\""}, "regular_string_literal$ebnf$1", {"literal":"\""}]},
    {"name": "regular_string_literal_characters", "symbols": ["regular_string_literal_character"]},
    {"name": "regular_string_literal_characters", "symbols": ["regular_string_literal_characters", "regular_string_literal_character"]},
    {"name": "regular_string_literal_character", "symbols": ["single_regular_string_literal_character"]},
    {"name": "regular_string_literal_character", "symbols": ["simple_escape_sequence"]},
    {"name": "regular_string_literal_character", "symbols": ["hexadecimal_escape_sequence"]},
    {"name": "regular_string_literal_character", "symbols": ["unicode_escape_sequence"]},
    {"name": "single_regular_string_literal_character", "symbols": [{"literal":"\""}], "postprocess": rejecter},
    {"name": "single_regular_string_literal_character", "symbols": [{"literal":"\\"}], "postprocess": rejecter},
    {"name": "single_regular_string_literal_character", "symbols": ["new_line_character"], "postprocess": rejecter},
    {"name": "single_regular_string_literal_character", "symbols": ["character"]},
    {"name": "verbatim_string_literal$string$1", "symbols": [{"literal":"@"}, {"literal":"\""}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "verbatim_string_literal$ebnf$1", "symbols": ["verbatim_string_literal_characters"], "postprocess": id},
    {"name": "verbatim_string_literal$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "verbatim_string_literal", "symbols": ["verbatim_string_literal$string$1", "verbatim_string_literal$ebnf$1", {"literal":"\""}]},
    {"name": "verbatim_string_literal_characters", "symbols": ["verbatim_string_literal_character"]},
    {"name": "verbatim_string_literal_characters", "symbols": ["verbatim_string_literal_characters", "verbatim_string_literal_character"]},
    {"name": "verbatim_string_literal_character", "symbols": ["single_verbatim_string_literal_character"]},
    {"name": "verbatim_string_literal_character", "symbols": ["quote_escape_sequence"]},
    {"name": "single_verbatim_string_literal_character", "symbols": [{"literal":"\""}], "postprocess": rejecter},
    {"name": "single_verbatim_string_literal_character", "symbols": ["character"]},
    {"name": "quote_escape_sequence$string$1", "symbols": [{"literal":"\""}, {"literal":"\""}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "quote_escape_sequence", "symbols": ["quote_escape_sequence$string$1"]},
    {"name": "null_literal$string$1", "symbols": [{"literal":"n"}, {"literal":"u"}, {"literal":"l"}, {"literal":"l"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "null_literal", "symbols": ["null_literal$string$1"]},
    {"name": "operator_or_punctuator", "symbols": [{"literal":"{"}]},
    {"name": "operator_or_punctuator", "symbols": [{"literal":"}"}]},
    {"name": "operator_or_punctuator", "symbols": [{"literal":"["}]},
    {"name": "operator_or_punctuator", "symbols": [{"literal":"]"}]},
    {"name": "operator_or_punctuator", "symbols": [{"literal":"("}]},
    {"name": "operator_or_punctuator", "symbols": [{"literal":")"}]},
    {"name": "operator_or_punctuator", "symbols": [{"literal":"."}]},
    {"name": "operator_or_punctuator", "symbols": [{"literal":","}]},
    {"name": "operator_or_punctuator", "symbols": [{"literal":":"}]},
    {"name": "operator_or_punctuator", "symbols": [{"literal":";"}]},
    {"name": "operator_or_punctuator", "symbols": [{"literal":"+"}]},
    {"name": "operator_or_punctuator", "symbols": [{"literal":"-"}]},
    {"name": "operator_or_punctuator", "symbols": [{"literal":"*"}]},
    {"name": "operator_or_punctuator", "symbols": [{"literal":"/"}]},
    {"name": "operator_or_punctuator", "symbols": [{"literal":"%"}]},
    {"name": "operator_or_punctuator", "symbols": [{"literal":"&"}]},
    {"name": "operator_or_punctuator", "symbols": [{"literal":"|"}]},
    {"name": "operator_or_punctuator", "symbols": [{"literal":"^"}]},
    {"name": "operator_or_punctuator", "symbols": [{"literal":"!"}]},
    {"name": "operator_or_punctuator", "symbols": [{"literal":"~"}]},
    {"name": "operator_or_punctuator", "symbols": [{"literal":"="}]},
    {"name": "operator_or_punctuator", "symbols": [{"literal":"<"}]},
    {"name": "operator_or_punctuator", "symbols": [{"literal":">"}]},
    {"name": "operator_or_punctuator", "symbols": [{"literal":"?"}]},
    {"name": "operator_or_punctuator$string$1", "symbols": [{"literal":"?"}, {"literal":"?"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "operator_or_punctuator", "symbols": ["operator_or_punctuator$string$1"]},
    {"name": "operator_or_punctuator$string$2", "symbols": [{"literal":":"}, {"literal":":"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "operator_or_punctuator", "symbols": ["operator_or_punctuator$string$2"]},
    {"name": "operator_or_punctuator$string$3", "symbols": [{"literal":"+"}, {"literal":"+"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "operator_or_punctuator", "symbols": ["operator_or_punctuator$string$3"]},
    {"name": "operator_or_punctuator$string$4", "symbols": [{"literal":"-"}, {"literal":"-"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "operator_or_punctuator", "symbols": ["operator_or_punctuator$string$4"]},
    {"name": "operator_or_punctuator$string$5", "symbols": [{"literal":"&"}, {"literal":"&"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "operator_or_punctuator", "symbols": ["operator_or_punctuator$string$5"]},
    {"name": "operator_or_punctuator$string$6", "symbols": [{"literal":"|"}, {"literal":"|"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "operator_or_punctuator", "symbols": ["operator_or_punctuator$string$6"]},
    {"name": "operator_or_punctuator$string$7", "symbols": [{"literal":"-"}, {"literal":">"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "operator_or_punctuator", "symbols": ["operator_or_punctuator$string$7"]},
    {"name": "operator_or_punctuator$string$8", "symbols": [{"literal":"="}, {"literal":"="}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "operator_or_punctuator", "symbols": ["operator_or_punctuator$string$8"]},
    {"name": "operator_or_punctuator$string$9", "symbols": [{"literal":"!"}, {"literal":"="}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "operator_or_punctuator", "symbols": ["operator_or_punctuator$string$9"]},
    {"name": "operator_or_punctuator$string$10", "symbols": [{"literal":"<"}, {"literal":"="}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "operator_or_punctuator", "symbols": ["operator_or_punctuator$string$10"]},
    {"name": "operator_or_punctuator$string$11", "symbols": [{"literal":">"}, {"literal":"="}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "operator_or_punctuator", "symbols": ["operator_or_punctuator$string$11"]},
    {"name": "operator_or_punctuator$string$12", "symbols": [{"literal":"+"}, {"literal":"="}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "operator_or_punctuator", "symbols": ["operator_or_punctuator$string$12"]},
    {"name": "operator_or_punctuator$string$13", "symbols": [{"literal":"-"}, {"literal":"="}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "operator_or_punctuator", "symbols": ["operator_or_punctuator$string$13"]},
    {"name": "operator_or_punctuator$string$14", "symbols": [{"literal":"*"}, {"literal":"="}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "operator_or_punctuator", "symbols": ["operator_or_punctuator$string$14"]},
    {"name": "operator_or_punctuator$string$15", "symbols": [{"literal":"/"}, {"literal":"="}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "operator_or_punctuator", "symbols": ["operator_or_punctuator$string$15"]},
    {"name": "operator_or_punctuator$string$16", "symbols": [{"literal":"%"}, {"literal":"="}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "operator_or_punctuator", "symbols": ["operator_or_punctuator$string$16"]},
    {"name": "operator_or_punctuator$string$17", "symbols": [{"literal":"&"}, {"literal":"="}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "operator_or_punctuator", "symbols": ["operator_or_punctuator$string$17"]},
    {"name": "operator_or_punctuator$string$18", "symbols": [{"literal":"|"}, {"literal":"="}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "operator_or_punctuator", "symbols": ["operator_or_punctuator$string$18"]},
    {"name": "operator_or_punctuator$string$19", "symbols": [{"literal":"^"}, {"literal":"="}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "operator_or_punctuator", "symbols": ["operator_or_punctuator$string$19"]},
    {"name": "operator_or_punctuator$string$20", "symbols": [{"literal":"<"}, {"literal":"<"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "operator_or_punctuator", "symbols": ["operator_or_punctuator$string$20"]},
    {"name": "operator_or_punctuator$string$21", "symbols": [{"literal":"<"}, {"literal":"<"}, {"literal":"="}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "operator_or_punctuator", "symbols": ["operator_or_punctuator$string$21"]},
    {"name": "right_shift$string$1", "symbols": [{"literal":">"}, {"literal":">"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "right_shift", "symbols": ["right_shift$string$1"]},
    {"name": "right_shift_assignment$string$1", "symbols": [{"literal":">"}, {"literal":">"}, {"literal":"="}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "right_shift_assignment", "symbols": ["right_shift_assignment$string$1"]},
    {"name": "pp_directive", "symbols": ["pp_declaration"]},
    {"name": "pp_directive", "symbols": ["pp_conditional"]},
    {"name": "pp_directive", "symbols": ["pp_line"]},
    {"name": "pp_directive", "symbols": ["pp_diagnostic"]},
    {"name": "pp_directive", "symbols": ["pp_region"]},
    {"name": "pp_directive", "symbols": ["pp_pragma"]},
    {"name": "conditional_symbol$string$1", "symbols": [{"literal":"t"}, {"literal":"r"}, {"literal":"u"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "conditional_symbol", "symbols": ["conditional_symbol$string$1"], "postprocess": rejecter},
    {"name": "conditional_symbol$string$2", "symbols": [{"literal":"f"}, {"literal":"a"}, {"literal":"l"}, {"literal":"s"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "conditional_symbol", "symbols": ["conditional_symbol$string$2"], "postprocess": rejecter},
    {"name": "conditional_symbol", "symbols": ["identifier_or_keyword"]},
    {"name": "pp_expression$ebnf$1", "symbols": ["whitespace"], "postprocess": id},
    {"name": "pp_expression$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "pp_expression$ebnf$2", "symbols": ["whitespace"], "postprocess": id},
    {"name": "pp_expression$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "pp_expression", "symbols": ["pp_expression$ebnf$1", "pp_or_expression", "pp_expression$ebnf$2"]},
    {"name": "pp_or_expression", "symbols": ["pp_and_expression"]},
    {"name": "pp_or_expression$ebnf$1", "symbols": ["whitespace"], "postprocess": id},
    {"name": "pp_or_expression$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "pp_or_expression$string$1", "symbols": [{"literal":"|"}, {"literal":"|"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "pp_or_expression$ebnf$2", "symbols": ["whitespace"], "postprocess": id},
    {"name": "pp_or_expression$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "pp_or_expression", "symbols": ["pp_or_expression", "pp_or_expression$ebnf$1", "pp_or_expression$string$1", "pp_or_expression$ebnf$2", "pp_and_expression"]},
    {"name": "pp_and_expression", "symbols": ["pp_equality_expression"]},
    {"name": "pp_and_expression$ebnf$1", "symbols": ["whitespace"], "postprocess": id},
    {"name": "pp_and_expression$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "pp_and_expression$string$1", "symbols": [{"literal":"&"}, {"literal":"&"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "pp_and_expression$ebnf$2", "symbols": ["whitespace"], "postprocess": id},
    {"name": "pp_and_expression$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "pp_and_expression", "symbols": ["pp_and_expression", "pp_and_expression$ebnf$1", "pp_and_expression$string$1", "pp_and_expression$ebnf$2", "pp_equality_expression"]},
    {"name": "pp_equality_expression", "symbols": ["pp_unary_expression"]},
    {"name": "pp_equality_expression$ebnf$1", "symbols": ["whitespace"], "postprocess": id},
    {"name": "pp_equality_expression$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "pp_equality_expression$string$1", "symbols": [{"literal":"="}, {"literal":"="}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "pp_equality_expression$ebnf$2", "symbols": ["whitespace"], "postprocess": id},
    {"name": "pp_equality_expression$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "pp_equality_expression", "symbols": ["pp_equality_expression", "pp_equality_expression$ebnf$1", "pp_equality_expression$string$1", "pp_equality_expression$ebnf$2", "pp_unary_expression"]},
    {"name": "pp_equality_expression$ebnf$3", "symbols": ["whitespace"], "postprocess": id},
    {"name": "pp_equality_expression$ebnf$3", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "pp_equality_expression$string$2", "symbols": [{"literal":"!"}, {"literal":"="}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "pp_equality_expression$ebnf$4", "symbols": ["whitespace"], "postprocess": id},
    {"name": "pp_equality_expression$ebnf$4", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "pp_equality_expression", "symbols": ["pp_equality_expression", "pp_equality_expression$ebnf$3", "pp_equality_expression$string$2", "pp_equality_expression$ebnf$4", "pp_unary_expression"]},
    {"name": "pp_unary_expression", "symbols": ["pp_primary_expression"]},
    {"name": "pp_unary_expression$ebnf$1", "symbols": ["whitespace"], "postprocess": id},
    {"name": "pp_unary_expression$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "pp_unary_expression", "symbols": [{"literal":"!"}, "pp_unary_expression$ebnf$1", "pp_unary_expression"]},
    {"name": "pp_primary_expression$string$1", "symbols": [{"literal":"t"}, {"literal":"r"}, {"literal":"u"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "pp_primary_expression", "symbols": ["pp_primary_expression$string$1"]},
    {"name": "pp_primary_expression$string$2", "symbols": [{"literal":"f"}, {"literal":"a"}, {"literal":"l"}, {"literal":"s"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "pp_primary_expression", "symbols": ["pp_primary_expression$string$2"]},
    {"name": "pp_primary_expression", "symbols": ["conditional_symbol"]},
    {"name": "pp_primary_expression$ebnf$1", "symbols": ["whitespace"], "postprocess": id},
    {"name": "pp_primary_expression$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "pp_primary_expression$ebnf$2", "symbols": ["whitespace"], "postprocess": id},
    {"name": "pp_primary_expression$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "pp_primary_expression", "symbols": [{"literal":"("}, "pp_primary_expression$ebnf$1", "pp_expression", "pp_primary_expression$ebnf$2", {"literal":")"}]},
    {"name": "pp_declaration$ebnf$1", "symbols": ["whitespace"], "postprocess": id},
    {"name": "pp_declaration$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "pp_declaration$ebnf$2", "symbols": ["whitespace"], "postprocess": id},
    {"name": "pp_declaration$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "pp_declaration$string$1", "symbols": [{"literal":"d"}, {"literal":"e"}, {"literal":"f"}, {"literal":"i"}, {"literal":"n"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "pp_declaration", "symbols": ["pp_declaration$ebnf$1", {"literal":"#"}, "pp_declaration$ebnf$2", "pp_declaration$string$1", "whitespace", "conditional_symbol", "pp_new_line"]},
    {"name": "pp_declaration$ebnf$3", "symbols": ["whitespace"], "postprocess": id},
    {"name": "pp_declaration$ebnf$3", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "pp_declaration$ebnf$4", "symbols": ["whitespace"], "postprocess": id},
    {"name": "pp_declaration$ebnf$4", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "pp_declaration$string$2", "symbols": [{"literal":"u"}, {"literal":"n"}, {"literal":"d"}, {"literal":"e"}, {"literal":"f"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "pp_declaration", "symbols": ["pp_declaration$ebnf$3", {"literal":"#"}, "pp_declaration$ebnf$4", "pp_declaration$string$2", "whitespace", "conditional_symbol", "pp_new_line"]},
    {"name": "pp_new_line$ebnf$1", "symbols": ["whitespace"], "postprocess": id},
    {"name": "pp_new_line$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "pp_new_line$ebnf$2", "symbols": ["single_line_comment"], "postprocess": id},
    {"name": "pp_new_line$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "pp_new_line", "symbols": ["pp_new_line$ebnf$1", "pp_new_line$ebnf$2", "new_line"]},
    {"name": "pp_conditional$ebnf$1", "symbols": ["pp_elif_sections"], "postprocess": id},
    {"name": "pp_conditional$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "pp_conditional$ebnf$2", "symbols": ["pp_else_section"], "postprocess": id},
    {"name": "pp_conditional$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "pp_conditional", "symbols": ["pp_if_section", "pp_conditional$ebnf$1", "pp_conditional$ebnf$2", "pp_endif"]},
    {"name": "pp_if_section$ebnf$1", "symbols": ["whitespace"], "postprocess": id},
    {"name": "pp_if_section$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "pp_if_section$ebnf$2", "symbols": ["whitespace"], "postprocess": id},
    {"name": "pp_if_section$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "pp_if_section$string$1", "symbols": [{"literal":"i"}, {"literal":"f"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "pp_if_section$ebnf$3", "symbols": ["conditional_section"], "postprocess": id},
    {"name": "pp_if_section$ebnf$3", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "pp_if_section", "symbols": ["pp_if_section$ebnf$1", {"literal":"#"}, "pp_if_section$ebnf$2", "pp_if_section$string$1", "whitespace", "pp_expression", "pp_new_line", "pp_if_section$ebnf$3"]},
    {"name": "pp_elif_sections", "symbols": ["pp_elif_section"]},
    {"name": "pp_elif_sections", "symbols": ["pp_elif_sections", "pp_elif_section"]},
    {"name": "pp_elif_section$ebnf$1", "symbols": ["whitespace"], "postprocess": id},
    {"name": "pp_elif_section$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "pp_elif_section$ebnf$2", "symbols": ["whitespace"], "postprocess": id},
    {"name": "pp_elif_section$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "pp_elif_section$string$1", "symbols": [{"literal":"e"}, {"literal":"l"}, {"literal":"i"}, {"literal":"f"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "pp_elif_section$ebnf$3", "symbols": ["conditional_section"], "postprocess": id},
    {"name": "pp_elif_section$ebnf$3", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "pp_elif_section", "symbols": ["pp_elif_section$ebnf$1", {"literal":"#"}, "pp_elif_section$ebnf$2", "pp_elif_section$string$1", "whitespace", "pp_expression", "pp_new_line", "pp_elif_section$ebnf$3"]},
    {"name": "pp_else_section$ebnf$1", "symbols": ["whitespace"], "postprocess": id},
    {"name": "pp_else_section$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "pp_else_section$ebnf$2", "symbols": ["whitespace"], "postprocess": id},
    {"name": "pp_else_section$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "pp_else_section$string$1", "symbols": [{"literal":"e"}, {"literal":"l"}, {"literal":"s"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "pp_else_section$ebnf$3", "symbols": ["conditional_section"], "postprocess": id},
    {"name": "pp_else_section$ebnf$3", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "pp_else_section", "symbols": ["pp_else_section$ebnf$1", {"literal":"#"}, "pp_else_section$ebnf$2", "pp_else_section$string$1", "pp_new_line", "pp_else_section$ebnf$3"]},
    {"name": "pp_endif$ebnf$1", "symbols": ["whitespace"], "postprocess": id},
    {"name": "pp_endif$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "pp_endif$ebnf$2", "symbols": ["whitespace"], "postprocess": id},
    {"name": "pp_endif$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "pp_endif$string$1", "symbols": [{"literal":"e"}, {"literal":"n"}, {"literal":"d"}, {"literal":"i"}, {"literal":"f"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "pp_endif", "symbols": ["pp_endif$ebnf$1", {"literal":"#"}, "pp_endif$ebnf$2", "pp_endif$string$1", "pp_new_line"]},
    {"name": "conditional_section", "symbols": ["input_section"]},
    {"name": "conditional_section", "symbols": ["skipped_section"]},
    {"name": "skipped_section", "symbols": ["skipped_section_part"]},
    {"name": "skipped_section", "symbols": ["skipped_section", "skipped_section_part"]},
    {"name": "skipped_section_part$ebnf$1", "symbols": ["skipped_characters"], "postprocess": id},
    {"name": "skipped_section_part$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "skipped_section_part", "symbols": ["skipped_section_part$ebnf$1", "new_line"]},
    {"name": "skipped_section_part", "symbols": ["pp_directive"]},
    {"name": "skipped_characters$ebnf$1", "symbols": ["whitespace"], "postprocess": id},
    {"name": "skipped_characters$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "skipped_characters$ebnf$2", "symbols": ["input_characters"], "postprocess": id},
    {"name": "skipped_characters$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "skipped_characters", "symbols": ["skipped_characters$ebnf$1", "not_number_sign", "skipped_characters$ebnf$2"]},
    {"name": "not_number_sign", "symbols": [{"literal":"#"}], "postprocess": rejecter},
    {"name": "not_number_sign", "symbols": ["input_character"]},
    {"name": "pp_diagnostic$ebnf$1", "symbols": ["whitespace"], "postprocess": id},
    {"name": "pp_diagnostic$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "pp_diagnostic$ebnf$2", "symbols": ["whitespace"], "postprocess": id},
    {"name": "pp_diagnostic$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "pp_diagnostic$string$1", "symbols": [{"literal":"e"}, {"literal":"r"}, {"literal":"r"}, {"literal":"o"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "pp_diagnostic", "symbols": ["pp_diagnostic$ebnf$1", {"literal":"#"}, "pp_diagnostic$ebnf$2", "pp_diagnostic$string$1", "pp_message"]},
    {"name": "pp_diagnostic$ebnf$3", "symbols": ["whitespace"], "postprocess": id},
    {"name": "pp_diagnostic$ebnf$3", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "pp_diagnostic$ebnf$4", "symbols": ["whitespace"], "postprocess": id},
    {"name": "pp_diagnostic$ebnf$4", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "pp_diagnostic$string$2", "symbols": [{"literal":"w"}, {"literal":"a"}, {"literal":"r"}, {"literal":"n"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "pp_diagnostic", "symbols": ["pp_diagnostic$ebnf$3", {"literal":"#"}, "pp_diagnostic$ebnf$4", "pp_diagnostic$string$2", "pp_message"]},
    {"name": "pp_message", "symbols": ["new_line"]},
    {"name": "pp_message$ebnf$1", "symbols": ["input_characters"], "postprocess": id},
    {"name": "pp_message$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "pp_message", "symbols": ["whitespace", "pp_message$ebnf$1", "new_line"]},
    {"name": "pp_region$ebnf$1", "symbols": ["conditional_section"], "postprocess": id},
    {"name": "pp_region$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "pp_region", "symbols": ["pp_start_region", "pp_region$ebnf$1", "pp_end_region"]},
    {"name": "pp_start_region$ebnf$1", "symbols": ["whitespace"], "postprocess": id},
    {"name": "pp_start_region$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "pp_start_region$ebnf$2", "symbols": ["whitespace"], "postprocess": id},
    {"name": "pp_start_region$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "pp_start_region$string$1", "symbols": [{"literal":"r"}, {"literal":"e"}, {"literal":"g"}, {"literal":"i"}, {"literal":"o"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "pp_start_region", "symbols": ["pp_start_region$ebnf$1", {"literal":"#"}, "pp_start_region$ebnf$2", "pp_start_region$string$1", "pp_message"]},
    {"name": "pp_end_region$ebnf$1", "symbols": ["whitespace"], "postprocess": id},
    {"name": "pp_end_region$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "pp_end_region$ebnf$2", "symbols": ["whitespace"], "postprocess": id},
    {"name": "pp_end_region$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "pp_end_region$string$1", "symbols": [{"literal":"e"}, {"literal":"n"}, {"literal":"d"}, {"literal":"r"}, {"literal":"e"}, {"literal":"g"}, {"literal":"i"}, {"literal":"o"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "pp_end_region", "symbols": ["pp_end_region$ebnf$1", {"literal":"#"}, "pp_end_region$ebnf$2", "pp_end_region$string$1", "pp_message"]},
    {"name": "pp_line$ebnf$1", "symbols": ["whitespace"], "postprocess": id},
    {"name": "pp_line$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "pp_line$ebnf$2", "symbols": ["whitespace"], "postprocess": id},
    {"name": "pp_line$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "pp_line$string$1", "symbols": [{"literal":"l"}, {"literal":"i"}, {"literal":"n"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "pp_line", "symbols": ["pp_line$ebnf$1", {"literal":"#"}, "pp_line$ebnf$2", "pp_line$string$1", "whitespace", "line_indicator", "pp_new_line"]},
    {"name": "line_indicator", "symbols": ["decimal_digits", "whitespace", "file_name"]},
    {"name": "line_indicator", "symbols": ["decimal_digits"]},
    {"name": "line_indicator$string$1", "symbols": [{"literal":"d"}, {"literal":"e"}, {"literal":"f"}, {"literal":"a"}, {"literal":"u"}, {"literal":"l"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "line_indicator", "symbols": ["line_indicator$string$1"]},
    {"name": "line_indicator$string$2", "symbols": [{"literal":"h"}, {"literal":"i"}, {"literal":"d"}, {"literal":"d"}, {"literal":"e"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "line_indicator", "symbols": ["line_indicator$string$2"]},
    {"name": "file_name", "symbols": [{"literal":"\""}, "file_name_characters", {"literal":"\""}]},
    {"name": "file_name_characters", "symbols": ["file_name_character"]},
    {"name": "file_name_characters", "symbols": ["file_name_characters", "file_name_character"]},
    {"name": "file_name_character", "symbols": [{"literal":"\""}], "postprocess": rejecter},
    {"name": "file_name_character", "symbols": ["new_line_character"], "postprocess": rejecter},
    {"name": "file_name_character", "symbols": ["input_character"]},
    {"name": "pp_pragma$ebnf$1", "symbols": ["whitespace"], "postprocess": id},
    {"name": "pp_pragma$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "pp_pragma$ebnf$2", "symbols": ["whitespace"], "postprocess": id},
    {"name": "pp_pragma$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "pp_pragma$string$1", "symbols": [{"literal":"p"}, {"literal":"r"}, {"literal":"a"}, {"literal":"g"}, {"literal":"m"}, {"literal":"a"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "pp_pragma", "symbols": ["pp_pragma$ebnf$1", {"literal":"#"}, "pp_pragma$ebnf$2", "pp_pragma$string$1", "pp_pragma_text"]},
    {"name": "pp_pragma_text", "symbols": ["new_line"]},
    {"name": "pp_pragma_text$ebnf$1", "symbols": ["input_characters"], "postprocess": id},
    {"name": "pp_pragma_text$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "pp_pragma_text", "symbols": ["whitespace", "pp_pragma_text$ebnf$1", "new_line"]}
]
  , ParserStart: "main"
}
if (typeof module !== 'undefined'&& typeof module.exports !== 'undefined') {
   module.exports = grammar;
} else {
   window.grammar = grammar;
}
})();
